ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -166,10 +166,12 @@ jobs:
           echo "### Installing cross-compile libraries for ${{ matrix.arch }} ###"
           sudo apt-get update
           if [ "${{ matrix.arch }}" == "aarch64" ]; then
-            sudo apt-get install -y libc6-dev-arm64-cross
+            sudo apt-get install -y libc6-dev-arm64-cross;
+            sudo apt-get install -y gcc-aarch64-linux-gnu
           elif [ "${{ matrix.arch }}" == "riscv64" ]; then
             # RISC-V 对应的包名是 libc6-dev-riscv64-cross
-            sudo apt-get install -y libc6-dev-riscv64-cross
+            sudo apt-get install -y libc6-dev-riscv64-cross;
+            sudo apt-get install -y gcc-riscv64-linux-gnu
           fi
 
       - name: Check aarch64-none-linux-gnu-gcc version
@@ -194,29 +196,29 @@ jobs:
      # === 步骤 3: 强制编译器使用新安装的库 ===
       # 通过注入 --sysroot 参数，我们明确告诉编译器使用上一步安装的库文件，
       # 从而避免任何路径混淆，并确保使用的是我们期望的版本。
-      - name: Patch Cross-Compile Command with Correct Sysroot
-        run: |
-          if [ "${{ matrix.arch }}" == "aarch64" ]; then
-            SYSROOT_PATH="/usr/aarch64-linux-gnu"
-            MAKE_SEARCH="make all ARCH=arm64"
-            MAKE_REPLACE="make all ARCH=arm64 CFLAGS='--sysroot=${SYSROOT_PATH}'"
-          elif [ "${{ matrix.arch }}" == "riscv64" ]; then
-            SYSROOT_PATH="/usr/riscv64-linux-gnu"
-            MAKE_SEARCH="make all ARCH=riscv64"
-            MAKE_REPLACE="make all ARCH=riscv64 CFLAGS='--sysroot=${SYSROOT_PATH}'"
-          else
-            echo "Unsupported architecture for patching: ${{ matrix.arch }}"
-            exit 1
-          fi
-          SCRIPT_PATH="platform/${{ matrix.arch }}/${{ matrix.board }}/test/systemtest/trootfs_deploy.sh"
-          if [ -f "$SCRIPT_PATH" ]; then
-            echo "Patching '$SCRIPT_PATH' to add correct sysroot for cross-compilation..."
-            sed -i "s|${MAKE_SEARCH}|${MAKE_REPLACE}|g" "$SCRIPT_PATH"
-            echo "Patch applied successfully. Patched content:"
-            grep --color=always "${MAKE_REPLACE}" "$SCRIPT_PATH"
-          else
-            echo "Warning: Build script $SCRIPT_PATH not found. Skipping patch."
-          fi
+      # - name: Patch Cross-Compile Command with Correct Sysroot
+      #   run: |
+      #     if [ "${{ matrix.arch }}" == "aarch64" ]; then
+      #       SYSROOT_PATH="/usr/aarch64-linux-gnu"
+      #       MAKE_SEARCH="make all ARCH=arm64"
+      #       MAKE_REPLACE="make all ARCH=arm64 CFLAGS='--sysroot=${SYSROOT_PATH}'"
+      #     elif [ "${{ matrix.arch }}" == "riscv64" ]; then
+      #       SYSROOT_PATH="/usr/riscv64-linux-gnu"
+      #       MAKE_SEARCH="make all ARCH=riscv64"
+      #       MAKE_REPLACE="make all ARCH=riscv64 CFLAGS='--sysroot=${SYSROOT_PATH}'"
+      #     else
+      #       echo "Unsupported architecture for patching: ${{ matrix.arch }}"
+      #       exit 1
+      #     fi
+      #     SCRIPT_PATH="platform/${{ matrix.arch }}/${{ matrix.board }}/test/systemtest/trootfs_deploy.sh"
+      #     if [ -f "$SCRIPT_PATH" ]; then
+      #       echo "Patching '$SCRIPT_PATH' to add correct sysroot for cross-compilation..."
+      #       sed -i "s|${MAKE_SEARCH}|${MAKE_REPLACE}|g" "$SCRIPT_PATH"
+      #       echo "Patch applied successfully. Patched content:"
+      #       grep --color=always "${MAKE_REPLACE}" "$SCRIPT_PATH"
+      #     else
+      #       echo "Warning: Build script $SCRIPT_PATH not found. Skipping patch."
+      #     fi
 
       - name: Run System Test
         run: make stest
